"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isAxiosError = exports.createErrorLog = exports.deleteErrorLog = exports.getErrorLog = exports.getErrorLogList = exports.http = void 0;
var http_1 = require("./http");
Object.defineProperty(exports, "http", { enumerable: true, get: function () { return http_1.http; } });
var errorLog_1 = require("./api/errorLog");
Object.defineProperty(exports, "getErrorLogList", { enumerable: true, get: function () { return errorLog_1.getErrorLogList; } });
Object.defineProperty(exports, "getErrorLog", { enumerable: true, get: function () { return errorLog_1.getErrorLog; } });
Object.defineProperty(exports, "deleteErrorLog", { enumerable: true, get: function () { return errorLog_1.deleteErrorLog; } });
Object.defineProperty(exports, "createErrorLog", { enumerable: true, get: function () { return errorLog_1.createErrorLog; } });
var helper_1 = require("./helper");
Object.defineProperty(exports, "isAxiosError", { enumerable: true, get: function () { return helper_1.isAxiosError; } });
